server:
    port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
#    passwod:
    enabled: true
  jpa:
    hibernate:  
        ddl-auto: update
        use-new-id-generator-mappings: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate.format_sql: true
      hibernate.show_sql: true
  jwt:
    secret: iokim#1220